default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: root

development:
  <<: *default
  database: pluto1

  


test:
  <<: *default
  database: pluto1_test


production:
  <<: *default
  database: pluto1_production
  username: pluto1
  password: root
